const WORD_BANK = {
  A: [
    { word: "abrazo", def: "Acción de rodear con los brazos a alguien en señal de cariño" },
    { word: "amanecer", def: "Momento del día en que empieza a aparecer la luz del sol" },
    { word: "alborada", def: "Tiempo de amanecer o primera luz del día" },
    { word: "audaz", def: "Que se atreve a realizar acciones arriesgadas o atrevidas" },
    { word: "arcilla", def: "Tierra compuesta de silicato de aluminio usada en alfarería" },
    { word: "almendra", def: "Fruto del almendro, comestible y de forma ovalada" },
    { word: "ancla", def: "Instrumento pesado de hierro que sujeta una embarcación" },
    { word: "armonía", def: "Combinación agradable de elementos o sonidos" },
    { word: "asombro", def: "Gran sorpresa o admiración" },
    { word: "ajedrez", def: "Juego de estrategia entre dos personas" },
    { word: "amuleto", def: "Objeto al que se atribuye protección o suerte" },
    { word: "árbol", def: "Planta alta de tronco leñoso" },
    { word: "águila", def: "Ave rapaz de gran tamaño" },
    { word: "atardecer", def: "Momento del día en que se pone el sol" },
    { word: "avalancha", def: "Desprendimiento masivo de nieve o piedras" },
    { word: "avenida", def: "Calle ancha de una ciudad" },
    { word: "abismo", def: "Gran profundidad o vacío" },
    { word: "acantilado", def: "Costa alta y escarpada" },
    { word: "adivinanza", def: "Acertijo propuesto como juego" },
    { word: "aguacero", def: "Lluvia intensa y repentina" },
    { word: "alquimia", def: "Práctica antigua vinculada a la transformación de la materia" },
    { word: "aldea", def: "Población pequeña" },
    { word: "aliento", def: "Aire que se expulsa al respirar" },
    { word: "altitud", def: "Altura respecto al nivel del mar" },
    { word: "aniversario", def: "Fecha en la que se cumple un año de algo" },
    { word: "aplauso", def: "Golpe de manos para mostrar aprobación" },
    { word: "apuesta", def: "Acuerdo sobre un resultado incierto" },
    { word: "aroma", def: "Olor agradable" },
    { word: "arquero", def: "Persona que dispara flechas o portero en algunos deportes" },
    { word: "artista", def: "Persona dedicada al arte" },
    { word: "ascenso", def: "Acción de subir" },
    { word: "asfalto", def: "Material usado para pavimentar" },
    { word: "aspiración", def: "Deseo intenso de lograr algo" },
    { word: "astilla", def: "Fragmento pequeño de madera" },
    { word: "astronauta", def: "Persona que viaja al espacio" },
    { word: "atleta", def: "Persona que practica deporte" },
    { word: "atmósfera", def: "Capa gaseosa que rodea la Tierra" },
    { word: "atracción", def: "Algo que despierta interés o gusto" },
    { word: "aurora", def: "Luz rosada que precede a la salida del sol" },
    { word: "autógrafo", def: "Firma de una persona" },
    { word: "aventura", def: "Experiencia arriesgada o emocionante" },
    { word: "aviador", def: "Persona que pilota aeronaves" },
    { word: "aviso", def: "Advertencia o noticia breve" },
    { word: "ayuno", def: "Privación voluntaria de comer" },
    { word: "azafrán", def: "Especia de color amarillo intenso" },
    { word: "azotea", def: "Parte superior de un edificio" },
    { word: "azúcar", def: "Sustancia dulce cristalizada" },
    { word: "azulejo", def: "Baldosa cerámica decorativa" },
    { word: "azul", def: "Color del cielo despejado" },
    { word: "azur", def: "Tono azul intenso" },
  ],
  B: [
    { word: "brújula", def: "Instrumento con aguja imantada que señala el norte" },
    { word: "bosque", def: "Gran extensión poblada de árboles" },
    { word: "belleza", def: "Cualidad de lo hermoso" },
    { word: "bodega", def: "Lugar donde se guarda vino" },
    { word: "bufanda", def: "Prenda de abrigo para el cuello" },
    { word: "bálsamo", def: "Sustancia que alivia o cura" },
    { word: "barco", def: "Embarcación para navegar" },
    { word: "burbuja", def: "Glóbulo de aire dentro de un líquido" },
    { word: "bisagra", def: "Pieza que permite abrir y cerrar" },
    { word: "bandera", def: "Tela que representa a una nación o grupo" },
    { word: "babero", def: "Prenda que protege la ropa al comer" },
    { word: "bahía", def: "Entrada amplia del mar en la costa" },
    { word: "baile", def: "Acción de bailar" },
    { word: "bala", def: "Proyectil disparado por un arma" },
    { word: "balanza", def: "Instrumento para pesar" },
    { word: "balcón", def: "Ventana saliente con barandilla" },
    { word: "balde", def: "Recipiente con asa" },
    { word: "ballena", def: "Mamífero marino de gran tamaño" },
    { word: "bambú", def: "Planta de tallo largo y hueco" },
    { word: "banquete", def: "Comida abundante y solemne" },
    { word: "baraja", def: "Conjunto de naipes" },
    { word: "baranda", def: "Protección lateral de escaleras o balcones" },
    { word: "barro", def: "Mezcla de tierra y agua" },
    { word: "barril", def: "Recipiente cilíndrico de madera o metal" },
    { word: "bastón", def: "Vara que sirve de apoyo" },
    { word: "batalla", def: "Combate entre fuerzas armadas" },
    { word: "batería", def: "Dispositivo que almacena energía" },
    { word: "bebida", def: "Líquido que se toma para beber" },
    { word: "beca", def: "Ayuda económica para estudiar" },
    { word: "bellota", def: "Fruto de la encina" },
    { word: "berenjena", def: "Hortaliza de piel morada" },
    { word: "bermuda", def: "Pantalón corto hasta la rodilla" },
    { word: "berrido", def: "Grito fuerte de ciertos animales" },
    { word: "biblia", def: "Libro sagrado del cristianismo" },
    { word: "bicicleta", def: "Vehículo de dos ruedas con pedales" },
    { word: "bigote", def: "Vello sobre el labio superior" },
    { word: "billete", def: "Papel moneda o título de viaje" },
    { word: "binoculares", def: "Instrumento óptico para ver de lejos" },
    { word: "biombo", def: "Panel plegable para separar espacios" },
    { word: "biografía", def: "Relato de la vida de una persona" },
    { word: "bizcocho", def: "Pastel esponjoso" },
    { word: "blanco", def: "Color de la nieve limpia" },
    { word: "blasón", def: "Escudo heráldico" },
    { word: "bloque", def: "Pieza grande y compacta" },
    { word: "blusa", def: "Prenda ligera de vestir" },
    { word: "boina", def: "Gorra redonda y plana" },
    { word: "boleto", def: "Documento que da derecho a entrar o viajar" },
    { word: "borrasca", def: "Perturbación atmosférica con mal tiempo" },
    { word: "botella", def: "Recipiente de vidrio o plástico" },
    { word: "bóveda", def: "Techo curvo de una construcción" },
  ],
  C: [
    { word: "crepúsculo", def: "Claridad entre el día y la noche" },
    { word: "cascada", def: "Caída de agua desde cierta altura" },
    { word: "canela", def: "Especia aromática" },
    { word: "ceniza", def: "Residuo gris de una combustión" },
    { word: "columna", def: "Soporte vertical" },
    { word: "cosecha", def: "Recolección de frutos" },
    { word: "cristal", def: "Vidrio fino y transparente" },
    { word: "calma", def: "Tranquilidad o ausencia de agitación" },
    { word: "cumbre", def: "Punto más alto de una montaña" },
    { word: "candado", def: "Cerradura portátil" },
    { word: "caballo", def: "Mamífero doméstico usado para montar" },
    { word: "cabaña", def: "Casa rústica pequeña" },
    { word: "cabra", def: "Animal doméstico de cuernos" },
    { word: "cacique", def: "Jefe de una comunidad indígena" },
    { word: "cactus", def: "Planta espinosa de zonas áridas" },
    { word: "cadena", def: "Serie de eslabones enlazados" },
    { word: "cafetera", def: "Utensilio o aparato para hacer café" },
    { word: "caimán", def: "Reptil parecido al cocodrilo" },
    { word: "caja", def: "Recipiente con tapa o sin ella" },
    { word: "calabozo", def: "Celda o prisión" },
    { word: "calendario", def: "Sistema para medir el tiempo por días y meses" },
    { word: "calle", def: "Vía urbana entre edificios" },
    { word: "camello", def: "Mamífero del desierto con jorobas" },
    { word: "camino", def: "Vía para transitar" },
    { word: "campana", def: "Instrumento metálico que suena al golpearse" },
    { word: "canario", def: "Ave pequeña de canto agradable" },
    { word: "canasto", def: "Cesta grande" },
    { word: "canción", def: "Composición musical con letra" },
    { word: "capitán", def: "Persona que manda una nave o equipo" },
    { word: "caracol", def: "Molusco de concha espiral" },
    { word: "carbón", def: "Material combustible negro" },
    { word: "caricia", def: "Contacto suave y afectuoso" },
    { word: "carpeta", def: "Cubierta para guardar papeles" },
    { word: "carretera", def: "Camino ancho para vehículos" },
    { word: "carta", def: "Escrito dirigido a una persona" },
    { word: "cartel", def: "Lámina con aviso o anuncio" },
    { word: "catedral", def: "Iglesia principal de una diócesis" },
    { word: "caverna", def: "Cueva grande" },
    { word: "cebolla", def: "Hortaliza de capas" },
    { word: "cedro", def: "Árbol alto de madera aromática" },
    { word: "cerro", def: "Elevación menor que una montaña" },
    { word: "chaleco", def: "Prenda sin mangas" },
    { word: "charco", def: "Acumulación pequeña de agua" },
    { word: "chispa", def: "Partícula encendida y brillante" },
    { word: "chimenea", def: "Conducto para humo o hogar con fuego" },
    { word: "chocolate", def: "Alimento obtenido del cacao" },
    { word: "cielo", def: "Espacio visible sobre la tierra" },
    { word: "ciruela", def: "Fruto del ciruelo" },
    { word: "ciudad", def: "Población grande" },
    { word: "claustro", def: "Galería cerrada de convento o patio interior" },
  ],
  D: [
    { word: "desierto", def: "Territorio con escasa vegetación y lluvias" },
    { word: "destino", def: "Lugar al que se dirige alguien" },
    { word: "diamante", def: "Piedra preciosa muy dura" },
    { word: "destreza", def: "Habilidad para hacer algo" },
    { word: "diluvio", def: "Lluvia muy copiosa" },
    { word: "delfín", def: "Mamífero marino inteligente" },
    { word: "diadema", def: "Adorno para la cabeza" },
    { word: "duende", def: "Ser fantástico pequeño" },
    { word: "dardo", def: "Arma arrojadiza pequeña" },
    { word: "docena", def: "Conjunto de doce unidades" },
    { word: "dado", def: "Cubo usado en juegos" },
    { word: "daga", def: "Arma blanca corta" },
    { word: "dalia", def: "Planta de flores vistosas" },
    { word: "danza", def: "Arte de bailar" },
    { word: "deber", def: "Obligación moral o escolar" },
    { word: "decoro", def: "Dignidad y compostura" },
    { word: "dedal", def: "Protector para coser" },
    { word: "dedo", def: "Parte alargada de la mano o pie" },
    { word: "defensa", def: "Acción de proteger" },
    { word: "delantal", def: "Prenda para proteger la ropa" },
    { word: "delta", def: "Terreno en la desembocadura de un río" },
    { word: "demora", def: "Retraso o tardanza" },
    { word: "denso", def: "Compacto o espeso" },
    { word: "dentista", def: "Profesional de la salud dental" },
    { word: "derecho", def: "Conjunto de leyes o lo opuesto a torcido" },
    { word: "derrame", def: "Salida accidental de un líquido" },
    { word: "derrota", def: "Pérdida en una competencia o batalla" },
    { word: "desafío", def: "Reto o prueba difícil" },
    { word: "desayuno", def: "Primera comida del día" },
    { word: "descanso", def: "Pausa para recuperar fuerzas" },
    { word: "deseo", def: "Ganas de obtener algo" },
    { word: "desfile", def: "Marcha organizada o exhibición" },
    { word: "deshielo", def: "Fusión del hielo o la nieve" },
    { word: "desierto", def: "Región árida con poca agua" },
    { word: "desnivel", def: "Diferencia de altura" },
    { word: "detalle", def: "Parte pequeña de un conjunto" },
    { word: "dibujo", def: "Representación hecha con líneas" },
    { word: "dictado", def: "Texto que alguien pronuncia para que otro escriba" },
    { word: "diente", def: "Pieza dura de la boca" },
    { word: "dieta", def: "Régimen de alimentación" },
    { word: "difunto", def: "Persona fallecida" },
    { word: "dinero", def: "Medio de intercambio" },
    { word: "disfraz", def: "Ropa para parecer otra cosa" },
    { word: "disparo", def: "Acción de lanzar un proyectil" },
    { word: "distancia", def: "Espacio entre dos puntos" },
    { word: "doblez", def: "Pliegue" },
    { word: "dolor", def: "Sensación molesta o sufrimiento" },
    { word: "domador", def: "Persona que amansa animales" },
    { word: "dormitorio", def: "Cuarto para dormir" },
    { word: "dragón", def: "Ser fantástico reptiliano" },
  ],
  E: [
    { word: "enigma", def: "Cosa difícil de comprender" },
    { word: "espejo", def: "Superficie que refleja imágenes" },
    { word: "estrella", def: "Astro con luz propia" },
    { word: "esmeralda", def: "Piedra preciosa verde" },
    { word: "escudo", def: "Arma defensiva o símbolo" },
    { word: "eclipse", def: "Ocultación de un astro" },
    { word: "equipaje", def: "Conjunto de maletas de un viaje" },
    { word: "escalera", def: "Serie de escalones" },
    { word: "emblema", def: "Símbolo representativo" },
    { word: "estación", def: "Cada una de las partes del año" },
    { word: "ebanista", def: "Persona que trabaja maderas finas" },
    { word: "ebrio", def: "Borracho" },
    { word: "eco", def: "Repetición de un sonido" },
    { word: "edificio", def: "Construcción destinada a varios usos" },
    { word: "editor", def: "Persona que publica o revisa textos" },
    { word: "educación", def: "Formación y enseñanza" },
    { word: "efecto", def: "Resultado producido por una causa" },
    { word: "ejército", def: "Conjunto de fuerzas militares" },
    { word: "ejemplo", def: "Caso que sirve de modelo" },
    { word: "elástico", def: "Que puede estirarse y volver" },
    { word: "elefante", def: "Mamífero grande con trompa" },
    { word: "elegancia", def: "Distinción y buen gusto" },
    { word: "elemento", def: "Parte integrante de un conjunto" },
    { word: "elixir", def: "Sustancia maravillosa o curativa" },
    { word: "embudo", def: "Utensilio para trasvasar líquidos" },
    { word: "emoción", def: "Alteración del ánimo" },
    { word: "encanto", def: "Atractivo o hechizo" },
    { word: "encina", def: "Árbol de hojas duras" },
    { word: "enemigo", def: "Persona contraria o rival" },
    { word: "energía", def: "Capacidad para realizar trabajo" },
    { word: "enlace", def: "Unión o vínculo" },
    { word: "ensayo", def: "Escrito breve o prueba" },
    { word: "entierro", def: "Acción de sepultar" },
    { word: "entorno", def: "Lo que rodea a alguien o algo" },
    { word: "envidia", def: "Tristeza por el bien ajeno" },
    { word: "epopeya", def: "Poema o hazaña heroica" },
    { word: "equilibrio", def: "Estado de compensación" },
    { word: "error", def: "Equivocación" },
    { word: "espada", def: "Arma blanca larga" },
    { word: "esfera", def: "Cuerpo redondo" },
    { word: "espiga", def: "Extremo del tallo de los cereales" },
    { word: "espina", def: "Púa de planta o pez" },
    { word: "espuma", def: "Conjunto de burbujas" },
    { word: "establo", def: "Lugar donde se guarda el ganado" },
    { word: "estampa", def: "Imagen impresa" },
    { word: "estuche", def: "Caja para guardar objetos" },
    { word: "etapa", def: "Fase o período" },
    { word: "eterno", def: "Que dura para siempre" },
    { word: "evaporación", def: "Paso de líquido a vapor" },
    { word: "exactitud", def: "Precisión" },
  ],
  F: [
    { word: "fábula", def: "Relato breve con enseñanza" },
    { word: "frontera", def: "Línea que separa territorios" },
    { word: "fragua", def: "Fogón para trabajar metales" },
    { word: "fénix", def: "Ave mitológica que renace" },
    { word: "flauta", def: "Instrumento musical de viento" },
    { word: "fortaleza", def: "Recinto fortificado" },
    { word: "fuente", def: "Lugar de donde brota agua" },
    { word: "farol", def: "Caja con luz en su interior" },
    { word: "felicidad", def: "Estado de gran satisfacción" },
    { word: "follaje", def: "Conjunto de hojas de una planta" },
    { word: "fábrica", def: "Lugar donde se producen objetos" },
    { word: "facción", def: "Rasgo del rostro o grupo parcial" },
    { word: "falda", def: "Prenda de vestir" },
    { word: "familia", def: "Conjunto de personas emparentadas" },
    { word: "fango", def: "Lodo espeso" },
    { word: "fantasma", def: "Aparición de un difunto" },
    { word: "fardo", def: "Paquete grande y apretado" },
    { word: "farmacia", def: "Establecimiento donde se venden medicinas" },
    { word: "faro", def: "Torre luminosa en la costa" },
    { word: "fatiga", def: "Cansancio" },
    { word: "fauna", def: "Conjunto de animales de una región" },
    { word: "febrero", def: "Segundo mes del año" },
    { word: "feudo", def: "Territorio de un señor feudal" },
    { word: "fibra", def: "Filamento o materia resistente" },
    { word: "ficción", def: "Invención imaginaria" },
    { word: "fidelidad", def: "Lealtad" },
    { word: "fiesta", def: "Celebración" },
    { word: "figura", def: "Forma o representación" },
    { word: "fila", def: "Serie ordenada de personas o cosas" },
    { word: "filo", def: "Borde cortante" },
    { word: "finca", def: "Propiedad rural o urbana" },
    { word: "firmeza", def: "Seguridad o estabilidad" },
    { word: "flama", def: "Llama de fuego" },
    { word: "flecha", def: "Proyectil con punta lanzado con arco" },
    { word: "flor", def: "Parte vistosa de muchas plantas" },
    { word: "fluido", def: "Sustancia que corre o se deforma" },
    { word: "fogata", def: "Fuego al aire libre" },
    { word: "folleto", def: "Impreso de pocas páginas" },
    { word: "fondo", def: "Parte más baja o profunda" },
    { word: "forja", def: "Trabajo del hierro a golpes" },
    { word: "forma", def: "Configuración exterior de algo" },
    { word: "forro", def: "Capa interior o cobertura" },
    { word: "foso", def: "Zanja profunda alrededor de una fortaleza" },
    { word: "foto", def: "Imagen tomada con cámara" },
    { word: "fracaso", def: "Resultado adverso" },
    { word: "fresa", def: "Fruta roja pequeña" },
    { word: "frío", def: "Baja temperatura" },
    { word: "fruta", def: "Parte comestible de una planta" },
    { word: "fuego", def: "Combustión con luz y calor" },
    { word: "futuro", def: "Tiempo que está por venir" },
  ],
  G: [
    { word: "galaxia", def: "Agrupación de millones de estrellas" },
    { word: "grieta", def: "Abertura alargada y estrecha" },
    { word: "guirnalda", def: "Tira de flores u hojas para adornar" },
    { word: "gacela", def: "Mamífero ágil y veloz" },
    { word: "granizo", def: "Precipitación de granos de hielo" },
    { word: "góndola", def: "Embarcación típica de Venecia" },
    { word: "glaciar", def: "Gran masa de hielo" },
    { word: "gremio", def: "Corporación de un oficio" },
    { word: "gárgola", def: "Figura de desagüe en edificios góticos" },
    { word: "guarida", def: "Refugio de animales o personas" },
    { word: "gabinete", def: "Cuarto pequeño o conjunto de ministros" },
    { word: "gafas", def: "Lentes para ver o proteger los ojos" },
    { word: "galería", def: "Pasillo largo o sala de exposición" },
    { word: "gallo", def: "Ave macho de corral" },
    { word: "galope", def: "Paso rápido del caballo" },
    { word: "gamba", def: "Crustáceo comestible" },
    { word: "ganado", def: "Conjunto de animales criados" },
    { word: "gancho", def: "Utensilio curvo para colgar" },
    { word: "garaje", def: "Lugar donde se guardan vehículos" },
    { word: "garbanzo", def: "Legumbre redondeada" },
    { word: "garra", def: "Uña fuerte de ave o fiera" },
    { word: "gas", def: "Estado de la materia sin forma propia" },
    { word: "gema", def: "Piedra preciosa" },
    { word: "gemido", def: "Quejido suave" },
    { word: "genio", def: "Talento extraordinario o ser fantástico" },
    { word: "geranio", def: "Planta ornamental" },
    { word: "gesto", def: "Movimiento del rostro o manos" },
    { word: "gigante", def: "Ser de tamaño enorme" },
    { word: "gimnasio", def: "Lugar para hacer ejercicio" },
    { word: "girasol", def: "Planta alta de flor amarilla" },
    { word: "globo", def: "Objeto hinchado o aeróstato" },
    { word: "gloria", def: "Fama o esplendor" },
    { word: "gol", def: "Tanto en algunos deportes" },
    { word: "golfo", def: "Gran entrada del mar en la tierra" },
    { word: "golondrina", def: "Ave migratoria de vuelo veloz" },
    { word: "goma", def: "Material elástico" },
    { word: "gorila", def: "Gran primate africano" },
    { word: "gorro", def: "Prenda para la cabeza" },
    { word: "gota", def: "Porción pequeña de líquido" },
    { word: "gozne", def: "Pieza articulada de una puerta" },
    { word: "grada", def: "Asiento escalonado de un estadio" },
    { word: "grama", def: "Hierba fina y corta" },
    { word: "granja", def: "Lugar de cultivo y cría de animales" },
    { word: "grifo", def: "Llave de paso de agua" },
    { word: "grillo", def: "Insecto saltador" },
    { word: "gruta", def: "Cueva pequeña" },
    { word: "guante", def: "Prenda para cubrir la mano" },
    { word: "guerra", def: "Lucha armada entre grupos o países" },
    { word: "guía", def: "Persona o texto que orienta" },
    { word: "guitarra", def: "Instrumento musical de cuerdas" },
  ],
  H: [
    { word: "horizonte", def: "Línea aparente entre cielo y tierra" },
    { word: "huella", def: "Marca que deja el pie o la mano" },
    { word: "hoguera", def: "Fuego hecho al aire libre" },
    { word: "hazaña", def: "Acción heroica o memorable" },
    { word: "herencia", def: "Bienes transmitidos tras una muerte" },
    { word: "herradura", def: "Pieza de hierro para cascos de caballos" },
    { word: "himno", def: "Composición musical solemne" },
    { word: "hiedra", def: "Planta trepadora de hojas perennes" },
    { word: "hamaca", def: "Red colgante para descansar" },
    { word: "hechizo", def: "Encantamiento o acto mágico" },
    { word: "haba", def: "Legumbre verde" },
    { word: "habitación", def: "Cuarto de una casa" },
    { word: "halcón", def: "Ave rapaz de vista aguda" },
    { word: "hallazgo", def: "Descubrimiento" },
    { word: "hambre", def: "Necesidad de comer" },
    { word: "harina", def: "Polvo obtenido de moler granos" },
    { word: "haya", def: "Árbol de tronco liso" },
    { word: "hélice", def: "Pieza con aspas giratorias" },
    { word: "hembra", def: "Sexo femenino de los animales" },
    { word: "herida", def: "Lesión abierta en el cuerpo" },
    { word: "hermano", def: "Persona que tiene los mismos padres" },
    { word: "héroe", def: "Persona admirada por sus hazañas" },
    { word: "herrero", def: "Persona que trabaja el hierro" },
    { word: "hielo", def: "Agua solidificada por el frío" },
    { word: "higiene", def: "Conjunto de prácticas para conservar la salud" },
    { word: "hilera", def: "Fila" },
    { word: "hilo", def: "Hebra larga y delgada" },
    { word: "historia", def: "Relato del pasado o narración" },
    { word: "hogar", def: "Casa o domicilio" },
    { word: "hoja", def: "Órgano plano de las plantas o lámina de papel" },
    { word: "hongo", def: "Ser vivo como la seta" },
    { word: "honor", def: "Cualidad moral y buena reputación" },
    { word: "hora", def: "Unidad de tiempo" },
    { word: "horno", def: "Aparato para cocer o calentar" },
    { word: "huerta", def: "Terreno de cultivo de verduras" },
    { word: "hueso", def: "Pieza rígida del esqueleto" },
    { word: "huevo", def: "Cuerpo esférico u oval de aves" },
    { word: "humedad", def: "Cantidad de agua en el aire o una cosa" },
    { word: "humilde", def: "Sencillo y sin orgullo" },
    { word: "humo", def: "Gas visible producto de una combustión" },
    { word: "huracán", def: "Viento muy fuerte giratorio" },
    { word: "hurto", def: "Robo sin violencia" },
    { word: "huso", def: "Utensilio para hilar o región horaria" },
    { word: "hospital", def: "Centro sanitario" },
    { word: "hostal", def: "Establecimiento de alojamiento" },
    { word: "humedal", def: "Terreno cubierto de agua" },
    { word: "hulla", def: "Carbón mineral" },
    { word: "humanidad", def: "Conjunto de los seres humanos" },
    { word: "hurón", def: "Mamífero doméstico alargado" },
    { word: "hidalguía", def: "Nobleza o generosidad" },
  ],
  I: [
    { word: "isla", def: "Porción de tierra rodeada de agua" },
    { word: "iceberg", def: "Gran masa de hielo flotante" },
    { word: "imán", def: "Cuerpo que atrae hierro" },
    { word: "ilusión", def: "Esperanza o alegría intensa" },
    { word: "ingenio", def: "Capacidad de inventar con habilidad" },
    { word: "incendio", def: "Fuego grande no controlado" },
    { word: "índice", def: "Lista ordenada de materias" },
    { word: "ídolo", def: "Imagen venerada o persona admirada" },
    { word: "iglesia", def: "Templo cristiano" },
    { word: "invisible", def: "Que no puede verse" },
    { word: "ibis", def: "Ave zancuda de pico curvo" },
    { word: "icono", def: "Símbolo o imagen representativa" },
    { word: "idea", def: "Representación mental" },
    { word: "idioma", def: "Lengua de un pueblo" },
    { word: "iglú", def: "Vivienda de nieve" },
    { word: "igualdad", def: "Condición de ser igual" },
    { word: "imaginación", def: "Facultad de crear imágenes mentales" },
    { word: "impulso", def: "Fuerza inicial o estímulo" },
    { word: "incenso", def: "Variante no recomendada de incienso" },
    { word: "incienso", def: "Sustancia aromática que se quema" },
    { word: "inclinar", def: "Mover algo hacia un lado" },
    { word: "inercia", def: "Tendencia a mantener un estado" },
    { word: "infancia", def: "Primera etapa de la vida" },
    { word: "infinito", def: "Que no tiene fin" },
    { word: "inflar", def: "Llenar de aire" },
    { word: "información", def: "Conjunto de datos" },
    { word: "ingeniera", def: "Mujer que ejerce ingeniería" },
    { word: "inhalar", def: "Tomar aire hacia dentro" },
    { word: "iniciativa", def: "Capacidad de empezar algo" },
    { word: "injerto", def: "Unión de una parte de planta con otra" },
    { word: "inmenso", def: "Muy grande" },
    { word: "inocencia", def: "Falta de culpa o malicia" },
    { word: "insecto", def: "Animal de seis patas" },
    { word: "insignia", def: "Distintivo honorífico" },
    { word: "instante", def: "Momento muy breve" },
    { word: "instrumento", def: "Objeto para realizar una acción" },
    { word: "intemperie", def: "Exposición al aire libre" },
    { word: "interior", def: "Parte de dentro" },
    { word: "invención", def: "Creación novedosa" },
    { word: "invierno", def: "Estación fría del año" },
    { word: "iris", def: "Parte coloreada del ojo o arco de colores" },
    { word: "ironía", def: "Modo de expresar lo contrario de lo que se dice" },
    { word: "irrupción", def: "Entrada brusca" },
    { word: "isótopo", def: "Variante atómica de un elemento" },
    { word: "itinerario", def: "Ruta prevista de un viaje" },
    { word: "izar", def: "Subir una bandera o vela" },
    { word: "imanación", def: "Emanación o salida sutil" },
    { word: "intuición", def: "Comprensión inmediata" },
    { word: "ideal", def: "Modelo perfecto o deseable" },
    { word: "impulsar", def: "Empujar o fomentar" },
  ],
  J: [
    { word: "joya", def: "Adorno de metal o piedras preciosas" },
    { word: "jardín", def: "Terreno con plantas ornamentales" },
    { word: "jirafa", def: "Mamífero africano de cuello largo" },
    { word: "jazmín", def: "Arbusto de flores blancas olorosas" },
    { word: "jornada", def: "Tiempo de trabajo diario" },
    { word: "jinete", def: "Persona que monta a caballo" },
    { word: "jabalí", def: "Cerdo salvaje" },
    { word: "juramento", def: "Promesa solemne" },
    { word: "júbilo", def: "Alegría intensa" },
    { word: "jeroglífico", def: "Escritura de signos y figuras" },
    { word: "jabón", def: "Sustancia para lavar" },
    { word: "jaula", def: "Recinto de barrotes para animales" },
    { word: "jefe", def: "Persona que manda" },
    { word: "jengibre", def: "Raíz aromática usada en cocina" },
    { word: "jineta", def: "Mamífero carnívoro parecido al gato" },
    { word: "jirón", def: "Pedazo rasgado de tela" },
    { word: "joba", def: "Bulto en la espalda" },
    { word: "jornada", def: "Duración del trabajo o del día" },
    { word: "joroba", def: "Protuberancia del lomo" },
    { word: "jota", def: "Nombre de la letra j o baile aragonés" },
    { word: "joven", def: "Persona de poca edad" },
    { word: "joyero", def: "Persona o caja que guarda joyas" },
    { word: "juego", def: "Actividad recreativa" },
    { word: "juez", def: "Persona que administra justicia" },
    { word: "jugo", def: "Líquido extraído de frutas" },
    { word: "julio", def: "Séptimo mes del año" },
    { word: "junco", def: "Planta de tallo flexible" },
    { word: "jungla", def: "Selva espesa" },
    { word: "junio", def: "Sexto mes del año" },
    { word: "junta", def: "Unión o reunión" },
    { word: "jurado", def: "Grupo que decide en concurso o juicio" },
    { word: "justicia", def: "Principio moral y legal de dar a cada uno lo suyo" },
    { word: "jabalína", def: "Hembra del jabalí" },
    { word: "jaleo", def: "Ruido o alboroto" },
    { word: "jamón", def: "Carne curada de cerdo" },
    { word: "jarra", def: "Recipiente para líquidos" },
    { word: "jazmín", def: "Flor blanca y perfumada" },
    { word: "jeta", def: "Cara en lenguaje coloquial" },
    { word: "jícara", def: "Taza pequeña" },
    { word: "jilguero", def: "Ave pequeña de canto agradable" },
    { word: "jinjol", def: "Fruto pequeño del azufaifo" },
    { word: "jirón", def: "Tira desgarrada" },
    { word: "jolgorio", def: "Fiesta ruidosa" },
    { word: "jornada", def: "Recorrido o período diario" },
    { word: "jorobado", def: "Que tiene joroba" },
    { word: "jovenzuela", def: "Muchacha joven" },
    { word: "joyel", def: "Joya pequeña y delicada" },
    { word: "juicio", def: "Facultad de pensar con sensatez" },
    { word: "jumbo", def: "Muy grande, en uso coloquial" },
    { word: "juncal", def: "Terreno poblado de juncos" },
  ],
  K: [
    { word: "kayak", def: "Embarcación ligera impulsada con remo de doble pala", contains: false },
    { word: "kilo", def: "Unidad de masa equivalente a mil gramos", contains: false },
    { word: "kiwi", def: "Fruto de pulpa verde y piel marrón", contains: false },
    { word: "koala", def: "Marsupial australiano que vive en eucaliptos", contains: false },
    { word: "karate", def: "Arte marcial japonés", contains: false },
    { word: "búnker", def: "Refugio subterráneo blindado", contains: true },
    { word: "vikingo", def: "Guerrero y navegante escandinavo", contains: true },
    { word: "bikini", def: "Prenda de baño femenina de dos piezas", contains: true },
    { word: "kermés", def: "Fiesta popular con puestos y juegos", contains: false },
    { word: "kétchup", def: "Salsa de tomate condimentada", contains: false },
    { word: "karma", def: "Consecuencia moral de los actos según creencias orientales", contains: false },
    { word: "kamikaze", def: "Piloto suicida japonés o persona temeraria", contains: false },
    { word: "kárate", def: "Variante acentuada de karate", contains: false },
    { word: "kilómetro", def: "Medida de longitud equivalente a mil metros", contains: false },
    { word: "karaoke", def: "Actividad de cantar sobre música grabada", contains: false },
    { word: "kayakista", def: "Persona que practica kayak", contains: false },
    { word: "kiosco", def: "Variante gráfica de quiosco", contains: false },
    { word: "kurdo", def: "Perteneciente al pueblo kurdo", contains: false },
    { word: "keniata", def: "Natural de Kenia", contains: false },
    { word: "kétmina", def: "Planta conocida como hibisco", contains: false },
    { word: "karaíta", def: "Miembro de una rama del judaísmo", contains: false },
    { word: "kuwaití", def: "Natural de Kuwait", contains: false },
    { word: "keroseno", def: "Combustible líquido derivado del petróleo", contains: false },
    { word: "kebab", def: "Comida de carne asada en brocheta", contains: false },
    { word: "kodak", def: "Nombre de marca usado a veces para cámara", contains: false },
    { word: "kril", def: "Conjunto de pequeños crustáceos marinos", contains: false },
    { word: "kappa", def: "Letra griega", contains: false },
    { word: "kenpo", def: "Arte marcial", contains: false },
    { word: "kendo", def: "Arte marcial japonés con espada", contains: false },
    { word: "kif", def: "Mezcla de resina o polen de cannabis", contains: false },
    { word: "koan", def: "Paradoja usada en la meditación zen", contains: false },
    { word: "klaxon", def: "Bocina o señal sonora", contains: false },
    { word: "kárstico", def: "Relativo a terrenos calcáreos erosionados", contains: false },
    { word: "kilovatio", def: "Unidad de potencia", contains: false },
    { word: "kilobyte", def: "Unidad informática de almacenamiento", contains: false },
    { word: "kurta", def: "Túnica usada en Asia meridional", contains: false },
    { word: "katana", def: "Espada japonesa curva", contains: false },
    { word: "kimono", def: "Vestimenta tradicional japonesa", contains: false },
    { word: "kilohercio", def: "Unidad de frecuencia", contains: false },
    { word: "kiosquero", def: "Persona que atiende un kiosco", contains: false },
    { word: "kefir", def: "Bebida láctea fermentada", contains: false },
    { word: "kárdex", def: "Registro o fichero organizado", contains: false },
    { word: "kayakismo", def: "Práctica deportiva del kayak", contains: false },
    { word: "koljós", def: "Granja colectiva soviética", contains: false },
    { word: "koiné", def: "Lengua común resultante de una mezcla", contains: false },
    { word: "krypton", def: "Gas noble", contains: false },
    { word: "karst", def: "Relieve calcáreo erosionado", contains: false },
    { word: "kraal", def: "Poblado cercado en África del sur", contains: false },
    { word: "kinesio", def: "Prefijo o uso relacionado con movimiento", contains: false },
    { word: "kilojulio", def: "Unidad de energía", contains: false },
  ],
  L: [
    { word: "laberinto", def: "Lugar de caminos confusos" },
    { word: "leyenda", def: "Narración tradicional y fantástica" },
    { word: "linterna", def: "Aparato portátil de luz" },
    { word: "lava", def: "Materia fundida de un volcán" },
    { word: "lápiz", def: "Instrumento para escribir o dibujar" },
    { word: "laguna", def: "Extensión de agua menor que un lago" },
    { word: "lluvia", def: "Precipitación de agua en gotas" },
    { word: "lucero", def: "Astro brillante, especialmente Venus" },
    { word: "lienzo", def: "Tela para pintar" },
    { word: "lobo", def: "Mamífero carnívoro salvaje" },
    { word: "labio", def: "Borde carnoso de la boca" },
    { word: "lacre", def: "Sustancia para sellar" },
    { word: "ladera", def: "Costado inclinado de un monte" },
    { word: "ladrillo", def: "Bloque de barro cocido para construir" },
    { word: "lagarto", def: "Reptil de cuerpo alargado" },
    { word: "lágrima", def: "Gota que sale de los ojos" },
    { word: "lamparilla", def: "Lámpara pequeña" },
    { word: "lanza", def: "Arma larga con punta" },
    { word: "lápida", def: "Piedra con inscripción funeraria" },
    { word: "larva", def: "Fase inicial de ciertos animales" },
    { word: "lástima", def: "Compasión o pena" },
    { word: "latido", def: "Golpe rítmico del corazón" },
    { word: "laurel", def: "Árbol aromático" },
    { word: "lavanda", def: "Planta aromática de flores violetas" },
    { word: "lector", def: "Persona que lee" },
    { word: "legumbre", def: "Semilla comestible como lenteja o garbanzo" },
    { word: "lejanía", def: "Gran distancia" },
    { word: "lengua", def: "Órgano de la boca o idioma" },
    { word: "león", def: "Gran felino" },
    { word: "letrina", def: "Lugar para evacuar" },
    { word: "levadura", def: "Sustancia que hace fermentar masas" },
    { word: "libélula", def: "Insecto alado de cuerpo alargado" },
    { word: "libertad", def: "Facultad de actuar sin opresión" },
    { word: "libro", def: "Conjunto de hojas encuadernadas" },
    { word: "licor", def: "Bebida alcohólica dulce" },
    { word: "lima", def: "Fruta cítrica o herramienta de limar" },
    { word: "limón", def: "Fruta amarilla y ácida" },
    { word: "lince", def: "Felino de vista aguda" },
    { word: "línea", def: "Trazo largo y continuo" },
    { word: "lirio", def: "Planta de flor vistosa" },
    { word: "lista", def: "Serie ordenada de elementos" },
    { word: "litera", def: "Cama superpuesta" },
    { word: "llama", def: "Fuego visible o animal andino" },
    { word: "llave", def: "Instrumento para abrir cerraduras" },
    { word: "lodo", def: "Barro blando" },
    { word: "lombriz", def: "Gusano de tierra" },
    { word: "lomo", def: "Parte superior del dorso" },
    { word: "lotería", def: "Juego de azar" },
    { word: "luna", def: "Satélite natural de la Tierra" },
    { word: "lustro", def: "Período de cinco años" },
  ],
  M: [
    { word: "misterio", def: "Cosa que no se puede explicar" },
    { word: "mariposa", def: "Insecto de alas vistosas" },
    { word: "muralla", def: "Muro alto para defender una ciudad" },
    { word: "melodía", def: "Sucesión agradable de sonidos" },
    { word: "montaña", def: "Gran elevación del terreno" },
    { word: "máscara", def: "Objeto que cubre el rostro" },
    { word: "molino", def: "Máquina para moler" },
    { word: "manantial", def: "Nacimiento de agua" },
    { word: "mosaico", def: "Obra hecha con pequeñas piezas de colores" },
    { word: "médula", def: "Sustancia blanda del interior de los huesos" },
    { word: "madera", def: "Materia sólida de los árboles" },
    { word: "madriguera", def: "Cueva o refugio de animales" },
    { word: "maestro", def: "Persona que enseña" },
    { word: "maíz", def: "Cereal de granos amarillos" },
    { word: "maleta", def: "Equipaje de viaje" },
    { word: "mamífero", def: "Animal que mama al nacer" },
    { word: "mano", def: "Parte del cuerpo al final del brazo" },
    { word: "mapa", def: "Representación geográfica" },
    { word: "mar", def: "Gran masa de agua salada" },
    { word: "marco", def: "Armazón que rodea algo" },
    { word: "marea", def: "Movimiento periódico del mar" },
    { word: "mármol", def: "Piedra pulida y resistente" },
    { word: "martillo", def: "Herramienta para golpear" },
    { word: "más", def: "Cantidad adicional" },
    { word: "matiz", def: "Gradación de color o diferencia sutil" },
    { word: "mayo", def: "Quinto mes del año" },
    { word: "mecha", def: "Hilo que arde en una vela" },
    { word: "medalla", def: "Pieza conmemorativa o premio" },
    { word: "medicina", def: "Sustancia para curar" },
    { word: "mercado", def: "Lugar de compraventa" },
    { word: "mesa", def: "Mueble con tablero" },
    { word: "meteorito", def: "Fragmento de cuerpo celeste caído en la Tierra" },
    { word: "metro", def: "Unidad de longitud o tren urbano" },
    { word: "mezcla", def: "Unión de elementos" },
    { word: "miel", def: "Sustancia dulce producida por abejas" },
    { word: "milagro", def: "Hecho extraordinario" },
    { word: "mina", def: "Excavación para extraer minerales" },
    { word: "minuto", def: "Unidad de tiempo" },
    { word: "mirada", def: "Acción de mirar" },
    { word: "misión", def: "Encargo importante" },
    { word: "mitad", def: "Una de dos partes iguales" },
    { word: "mochila", def: "Bolsa que se lleva a la espalda" },
    { word: "moneda", def: "Pieza de metal con valor" },
    { word: "mono", def: "Primate" },
    { word: "morado", def: "Color entre azul y rojo" },
    { word: "morro", def: "Hocico o parte saliente" },
    { word: "mosca", def: "Insecto volador común" },
    { word: "música", def: "Arte de combinar sonidos" },
    { word: "musgo", def: "Planta pequeña de lugares húmedos" },
    { word: "mutación", def: "Cambio en genes o formas" },
  ],
  N: [
    { word: "naufragio", def: "Hundimiento de una embarcación" },
    { word: "niebla", def: "Nube baja que dificulta ver" },
    { word: "nómada", def: "Que no tiene residencia fija" },
    { word: "navaja", def: "Cuchillo plegable" },
    { word: "néctar", def: "Líquido azucarado de las flores" },
    { word: "nevada", def: "Caída abundante de nieve" },
    { word: "nostalgia", def: "Tristeza por un recuerdo lejano" },
    { word: "nube", def: "Masa de vapor de agua en el aire" },
    { word: "nudo", def: "Lazo que se aprieta" },
    { word: "nácar", def: "Capa interna brillante de ciertas conchas" },
    { word: "nación", def: "Conjunto de habitantes de un país" },
    { word: "nadal", def: "Relativo a la Navidad" },
    { word: "naipe", def: "Carta de la baraja" },
    { word: "nariz", def: "Órgano del olfato" },
    { word: "natación", def: "Acción o deporte de nadar" },
    { word: "natural", def: "Propio de la naturaleza" },
    { word: "navidad", def: "Fiesta del nacimiento de Jesús" },
    { word: "neblina", def: "Niebla ligera" },
    { word: "necio", def: "Falto de inteligencia o terco" },
    { word: "negocio", def: "Actividad comercial" },
    { word: "negro", def: "Color de la oscuridad" },
    { word: "nenúfar", def: "Planta acuática de grandes hojas" },
    { word: "neón", def: "Gas noble o luz brillante" },
    { word: "nervio", def: "Fibra que transmite impulsos" },
    { word: "neto", def: "Claro o resultante sin descuentos" },
    { word: "neutrón", def: "Partícula sin carga del átomo" },
    { word: "nido", def: "Refugio de las aves" },
    { word: "nieve", def: "Agua congelada en copos" },
    { word: "ninguno", def: "Ni uno solo" },
    { word: "ninfa", def: "Divinidad femenina de la naturaleza" },
    { word: "nivel", def: "Altura o categoría" },
    { word: "nobleza", def: "Calidad de noble o grupo noble" },
    { word: "noche", def: "Tiempo sin luz solar" },
    { word: "noción", def: "Conocimiento elemental" },
    { word: "nogal", def: "Árbol que da nueces" },
    { word: "noria", def: "Máquina para sacar agua o rueda de feria" },
    { word: "norma", def: "Regla que debe seguirse" },
    { word: "norte", def: "Uno de los puntos cardinales" },
    { word: "nota", def: "Apunte breve o sonido musical" },
    { word: "novela", def: "Narración literaria extensa" },
    { word: "noviembre", def: "Undécimo mes del año" },
    { word: "novio", def: "Persona que mantiene relación amorosa" },
    { word: "nuez", def: "Fruto seco del nogal" },
    { word: "número", def: "Expresión de cantidad" },
    { word: "nutria", def: "Mamífero acuático" },
    { word: "náufrago", def: "Persona que sobrevive a un naufragio" },
    { word: "níquel", def: "Metal blanquecino" },
    { word: "náyade", def: "Ninfa de aguas dulces" },
    { word: "neruda", def: "Apellido convertido en referencia cultural", contains: true },
    { word: "nacarado", def: "De brillo parecido al nácar" },
  ],
  "Ñ": [
    { word: "ñoqui", def: "Pasta alimenticia hecha con patata, harina y huevo", contains: false },
    { word: "ñandú", def: "Ave corredora sudamericana", contains: false },
    { word: "ñoño", def: "Excesivamente remilgado o soso", contains: false },
    { word: "cabaña", def: "Casa pequeña y rústica", contains: true },
    { word: "pañuelo", def: "Trozo de tela para limpiarse o adornarse", contains: true },
    { word: "montaña", def: "Gran elevación natural del terreno", contains: true },
    { word: "araña", def: "Artrópodo de ocho patas que teje telas", contains: true },
    { word: "muñeca", def: "Juguete con forma humana o articulación de la mano", contains: true },
    { word: "pestaña", def: "Pelo del borde del párpado", contains: true },
    { word: "leña", def: "Madera para hacer fuego", contains: true },
    { word: "ñoñería", def: "Actitud o cosa propia de alguien ñoño", contains: false },
    { word: "ñu", def: "Mamífero africano parecido al buey", contains: false },
    { word: "piñata", def: "Recipiente lleno de dulces que se rompe en fiestas", contains: true },
    { word: "uña", def: "Lámina dura en la punta de los dedos", contains: true },
    { word: "cañón", def: "Tubo de arma o desfiladero profundo", contains: true },
    { word: "niñez", def: "Etapa infantil de la vida", contains: true },
    { word: "daño", def: "Perjuicio o deterioro", contains: true },
    { word: "señal", def: "Marca o indicio", contains: true },
    { word: "bañera", def: "Recipiente para bañarse", contains: true },
    { word: "compañía", def: "Sociedad mercantil o presencia de otra persona", contains: true },
    { word: "ensueño", def: "Sueño o fantasía agradable", contains: true },
    { word: "guiño", def: "Cierre rápido de un ojo", contains: true },
    { word: "rebaño", def: "Conjunto de ovejas", contains: true },
    { word: "moño", def: "Lazo o peinado recogido", contains: true },
    { word: "riñón", def: "Órgano que filtra la sangre", contains: true },
    { word: "señuelo", def: "Objeto que sirve para atraer", contains: true },
    { word: "tañido", def: "Sonido de una campana", contains: true },
    { word: "ñora", def: "Pimiento rojo seco", contains: false },
    { word: "ñame", def: "Tubérculo comestible", contains: false },
    { word: "ñaque", def: "Compañía teatral muy pobre", contains: false },
    { word: "otoñal", def: "Propio del otoño", contains: true },
    { word: "extraño", def: "Raro o desconocido", contains: true },
    { word: "apaña", def: "Forma verbal de apañar", contains: true },
    { word: "engaño", def: "Falta de verdad para inducir error", contains: true },
    { word: "pañal", def: "Prenda absorbente para bebés", contains: true },
    { word: "rasguño", def: "Herida superficial hecha con uñas", contains: true },
    { word: "señor", def: "Tratamiento de respeto para un hombre", contains: true },
    { word: "señora", def: "Tratamiento de respeto para una mujer", contains: true },
    { word: "campaña", def: "Conjunto de actos para lograr un fin", contains: true },
    { word: "español", def: "Natural de España o lengua de España", contains: true },
    { word: "entraña", def: "Parte interior o afecto profundo", contains: true },
    { word: "sueño", def: "Acto de dormir o lo soñado", contains: true },
    { word: "teñir", def: "Dar color a una cosa", contains: true },
    { word: "aliño", def: "Condimento o adorno", contains: true },
    { word: "ceñir", def: "Rodear o ajustar al cuerpo", contains: true },
    { word: "desdeñar", def: "Mostrar desprecio", contains: true },
    { word: "acuñar", def: "Imprimir o grabar una moneda", contains: true },
    { word: "reñir", def: "Discutir o reprender", contains: true },
    { word: "añejo", def: "Que tiene muchos años", contains: true },
    { word: "ñoñez", def: "Cualidad de ñoño o niñez temprana según contexto", contains: false },
  ],
  O: [
    { word: "oasis", def: "Lugar con agua y vegetación en el desierto" },
    { word: "orquesta", def: "Conjunto de músicos" },
    { word: "oleaje", def: "Movimiento de las olas del mar" },
    { word: "oruga", def: "Larva de mariposa" },
    { word: "oxígeno", def: "Elemento esencial para la respiración" },
    { word: "odisea", def: "Viaje con muchas aventuras" },
    { word: "ópera", def: "Obra teatral cantada" },
    { word: "otoño", def: "Estación entre verano e invierno" },
    { word: "olivo", def: "Árbol que da aceitunas" },
    { word: "olvido", def: "Pérdida de memoria sobre algo" },
    { word: "obelisco", def: "Monumento alto de cuatro caras" },
    { word: "objeto", def: "Cosa material" },
    { word: "obra", def: "Trabajo realizado o creación artística" },
    { word: "obrero", def: "Trabajador manual" },
    { word: "obsidiana", def: "Vidrio volcánico negro" },
    { word: "ocaso", def: "Puesta del sol" },
    { word: "océano", def: "Gran extensión de agua salada" },
    { word: "ochavo", def: "Moneda antigua o pequeña porción" },
    { word: "oculista", def: "Especialista de los ojos" },
    { word: "oferta", def: "Propuesta o precio rebajado" },
    { word: "oficio", def: "Profesión o comunicación escrita" },
    { word: "ojeada", def: "Mirada rápida" },
    { word: "ojera", def: "Sombra bajo los ojos" },
    { word: "ojo", def: "Órgano de la vista" },
    { word: "ola", def: "Movimiento del agua" },
    { word: "oleoducto", def: "Tubería para transportar petróleo" },
    { word: "olfato", def: "Sentido para percibir olores" },
    { word: "olmo", def: "Árbol de tronco robusto" },
    { word: "olor", def: "Impresión producida en el olfato" },
    { word: "ombligo", def: "Cicatriz en el centro del vientre" },
    { word: "onda", def: "Movimiento oscilatorio o forma curva" },
    { word: "ónice", def: "Piedra semipreciosa" },
    { word: "opción", def: "Posibilidad de elegir" },
    { word: "óptica", def: "Rama de la física de la luz" },
    { word: "oración", def: "Rezo o enunciado gramatical" },
    { word: "orbe", def: "Mundo o esfera" },
    { word: "orden", def: "Colocación adecuada o mandato" },
    { word: "oreja", def: "Parte externa del oído" },
    { word: "orfebre", def: "Artista que trabaja metales preciosos" },
    { word: "orilla", def: "Borde del agua" },
    { word: "oro", def: "Metal precioso amarillo" },
    { word: "orquesta", def: "Agrupación de instrumentos y músicos" },
    { word: "ortiga", def: "Planta que produce escozor" },
    { word: "oso", def: "Mamífero grande y fuerte" },
    { word: "ostra", def: "Molusco de concha rugosa" },
    { word: "otorgar", def: "Conceder algo" },
    { word: "oveja", def: "Animal doméstico lanudo" },
    { word: "óxido", def: "Compuesto de oxígeno con otro elemento" },
    { word: "ozono", def: "Gas presente en la atmósfera" },
    { word: "occidente", def: "Punto cardinal donde se pone el sol" },
  ],
  P: [
    { word: "penumbra", def: "Sombra débil entre luz y oscuridad" },
    { word: "pergamino", def: "Piel preparada para escribir" },
    { word: "pirata", def: "Ladrón de barcos" },
    { word: "pradera", def: "Terreno llano cubierto de hierba" },
    { word: "pirámide", def: "Construcción monumental de base ancha" },
    { word: "paradoja", def: "Idea aparentemente contradictoria" },
    { word: "paraguas", def: "Utensilio para protegerse de la lluvia" },
    { word: "paloma", def: "Ave símbolo de la paz" },
    { word: "pólvora", def: "Mezcla explosiva" },
    { word: "puerto", def: "Lugar de abrigo para embarcaciones" },
    { word: "pabellón", def: "Edificio aislado o bandera nacional" },
    { word: "paciencia", def: "Capacidad de esperar sin alterarse" },
    { word: "pacto", def: "Acuerdo entre partes" },
    { word: "padre", def: "Progenitor masculino" },
    { word: "paisaje", def: "Extensión de terreno vista desde un punto" },
    { word: "paja", def: "Tallo seco de cereal" },
    { word: "palacio", def: "Edificio suntuoso" },
    { word: "paleta", def: "Tabla de colores o helado de palo" },
    { word: "palmera", def: "Árbol de tronco recto y copa de hojas largas" },
    { word: "pánico", def: "Miedo intenso" },
    { word: "pantalla", def: "Superficie donde se proyecta o muestra imagen" },
    { word: "papel", def: "Lámina fina hecha de pasta vegetal" },
    { word: "paquete", def: "Bulto envuelto" },
    { word: "parcela", def: "Porción pequeña de terreno" },
    { word: "pared", def: "Muro vertical" },
    { word: "parque", def: "Terreno con árboles para recreo" },
    { word: "párrafo", def: "Fragmento de texto" },
    { word: "pasarela", def: "Puente o camino elevado" },
    { word: "pasión", def: "Sentimiento intenso" },
    { word: "pastel", def: "Dulce horneado" },
    { word: "paz", def: "Situación sin guerra ni violencia" },
    { word: "peaje", def: "Pago por usar una vía" },
    { word: "pedestal", def: "Base que sostiene una estatua" },
    { word: "peldaño", def: "Cada escalón" },
    { word: "pelícano", def: "Ave acuática de gran pico" },
    { word: "pelota", def: "Objeto esférico para jugar" },
    { word: "pensamiento", def: "Idea producida por la mente" },
    { word: "pepita", def: "Semilla pequeña o trozo de oro" },
    { word: "perfume", def: "Sustancia aromática" },
    { word: "perla", def: "Concreción brillante producida por moluscos" },
    { word: "perro", def: "Mamífero doméstico muy común" },
    { word: "pescador", def: "Persona que pesca" },
    { word: "pétalo", def: "Hoja coloreada de una flor" },
    { word: "piedra", def: "Fragmento duro de roca" },
    { word: "pincel", def: "Utensilio para pintar" },
    { word: "pino", def: "Árbol de hojas aciculares" },
    { word: "plaza", def: "Espacio amplio en una ciudad" },
    { word: "pluma", def: "Estructura de las aves o instrumento para escribir" },
    { word: "poema", def: "Composición literaria en verso" },
    { word: "puente", def: "Construcción para pasar sobre un obstáculo" },
  ],
  Q: [
    { word: "quimera", def: "Ilusión difícil o monstruo mitológico" },
    { word: "quilate", def: "Medida de peso o pureza del oro" },
    { word: "queso", def: "Alimento obtenido de la leche cuajada" },
    { word: "quijote", def: "Persona idealista y generosa" },
    { word: "quintal", def: "Medida antigua de peso" },
    { word: "querella", def: "Acusación ante un juez" },
    { word: "quiosco", def: "Puesto pequeño de venta" },
    { word: "quietud", def: "Estado de reposo" },
    { word: "quebrada", def: "Paso hondo entre montañas" },
    { word: "quedar", def: "Permanecer o convenir encuentro" },
    { word: "queja", def: "Expresión de disgusto" },
    { word: "quemadura", def: "Lesión producida por calor" },
    { word: "querer", def: "Tener afecto o deseo" },
    { word: "quesería", def: "Lugar donde se fabrica queso" },
    { word: "quicio", def: "Parte de puerta donde se ajusta" },
    { word: "quiebre", def: "Rotura o descenso brusco" },
    { word: "quijada", def: "Mandíbula" },
    { word: "quilómetro", def: "Mil metros" },
    { word: "química", def: "Ciencia de la composición de la materia" },
    { word: "quimono", def: "Variante no recomendada de kimono", contains: true },
    { word: "quiniela", def: "Apuesta sobre resultados deportivos" },
    { word: "quinta", def: "Casa de recreo en el campo" },
    { word: "quiosquero", def: "Persona que atiende un quiosco" },
    { word: "quirófano", def: "Sala de operaciones" },
    { word: "quiste", def: "Bolsa cerrada en un tejido" },
    { word: "quitamanchas", def: "Producto para eliminar manchas" },
    { word: "quitar", def: "Apartar o sacar" },
    { word: "quite", def: "Lance de toreo o acción de apartar un peligro" },
    { word: "quizá", def: "Tal vez" },
    { word: "quórum", def: "Número mínimo para sesionar" },
    { word: "quebanto", def: "Dolor o deterioro" },
    { word: "quelonio", def: "Reptil como la tortuga" },
    { word: "quemazón", def: "Sensación de ardor" },
    { word: "querubín", def: "Ángel niño" },
    { word: "quesadilla", def: "Preparación con queso" },
    { word: "quiromancia", def: "Adivinación por la mano" },
    { word: "quitasol", def: "Sombrilla grande" },
    { word: "quitrán", def: "Sustancia negra y viscosa" },
    { word: "quincena", def: "Período de quince días" },
    { word: "quingombó", def: "Planta comestible tropical" },
    { word: "quebrar", def: "Romper o arruinar" },
    { word: "quehacer", def: "Tarea u ocupación" },
    { word: "quemar", def: "Consumir con fuego" },
    { word: "queroseno", def: "Combustible derivado del petróleo", contains: true },
    { word: "quesito", def: "Porción pequeña de queso" },
    { word: "quiero", def: "Primera persona de querer" },
    { word: "quieto", def: "Sin moverse" },
    { word: "quimérico", def: "Fantástico o irrealizable" },
    { word: "quinqué", def: "Lámpara antigua de aceite" },
    { word: "quirate", def: "Variante de quilate" },
  ],
  R: [
    { word: "relámpago", def: "Resplandor de una descarga eléctrica" },
    { word: "remolino", def: "Movimiento giratorio rápido" },
    { word: "rocío", def: "Gotitas que se forman sobre plantas" },
    { word: "reliquia", def: "Objeto antiguo venerado" },
    { word: "refugio", def: "Lugar de protección" },
    { word: "rescoldo", def: "Brasa pequeña bajo la ceniza" },
    { word: "ruiseñor", def: "Pájaro de canto melodioso" },
    { word: "raíz", def: "Parte de la planta bajo tierra" },
    { word: "rompecabezas", def: "Juego de piezas para recomponer una figura" },
    { word: "rústico", def: "Sencillo y campestre" },
    { word: "rábano", def: "Raíz comestible picante" },
    { word: "racha", def: "Golpe de viento o serie continuada" },
    { word: "radio", def: "Aparato de sonido o segmento desde el centro" },
    { word: "rama", def: "Parte del árbol que sale del tronco" },
    { word: "ramillete", def: "Conjunto pequeño de flores" },
    { word: "ranura", def: "Abertura estrecha" },
    { word: "rapidez", def: "Velocidad" },
    { word: "rasgo", def: "Característica o trazo" },
    { word: "rastro", def: "Huella o señal dejada" },
    { word: "rayo", def: "Descarga eléctrica o línea de luz" },
    { word: "rebaño", def: "Conjunto de ganado" },
    { word: "receta", def: "Instrucciones para cocinar o medicar" },
    { word: "recreo", def: "Descanso o diversión" },
    { word: "red", def: "Tejido de mallas o sistema conectado" },
    { word: "regalo", def: "Obsequio" },
    { word: "regla", def: "Norma o instrumento recto" },
    { word: "reina", def: "Esposa del rey o pieza del ajedrez" },
    { word: "reloj", def: "Instrumento para medir el tiempo" },
    { word: "remo", def: "Utensilio para impulsar embarcaciones" },
    { word: "rencor", def: "Resentimiento persistente" },
    { word: "reno", def: "Mamífero de regiones frías" },
    { word: "repisa", def: "Tabla saliente en una pared" },
    { word: "rescate", def: "Acción de salvar o recuperar" },
    { word: "resina", def: "Sustancia pegajosa vegetal" },
    { word: "respeto", def: "Consideración hacia alguien o algo" },
    { word: "retablo", def: "Estructura decorada detrás de un altar" },
    { word: "reto", def: "Desafío" },
    { word: "retrato", def: "Representación de una persona" },
    { word: "reunión", def: "Encuentro de varias personas" },
    { word: "revista", def: "Publicación periódica" },
    { word: "riego", def: "Acción de echar agua a cultivos" },
    { word: "rienda", def: "Correa para guiar caballos" },
    { word: "riesgo", def: "Posibilidad de daño" },
    { word: "rincón", def: "Ángulo interior o lugar apartado" },
    { word: "río", def: "Corriente natural de agua" },
    { word: "risa", def: "Expresión sonora de alegría" },
    { word: "ritmo", def: "Orden acompasado" },
    { word: "roble", def: "Árbol de madera fuerte" },
    { word: "ronda", def: "Recorrido o serie sucesiva" },
    { word: "rubí", def: "Piedra preciosa roja" },
  ],
  S: [
    { word: "sirena", def: "Ser mitológico con cola de pez" },
    { word: "sendero", def: "Camino estrecho" },
    { word: "sombra", def: "Oscuridad causada por un cuerpo opaco" },
    { word: "suspiro", def: "Respiración profunda y audible" },
    { word: "semilla", def: "Parte del fruto con el embrión de una planta" },
    { word: "sinfonía", def: "Composición musical para orquesta" },
    { word: "sortija", def: "Anillo" },
    { word: "sótano", def: "Pieza subterránea de un edificio" },
    { word: "soplo", def: "Acción de echar aire por la boca" },
    { word: "surco", def: "Hendidura en la tierra" },
    { word: "sábana", def: "Tela que cubre la cama" },
    { word: "sable", def: "Espada curva" },
    { word: "sacerdote", def: "Ministro de un culto" },
    { word: "saco", def: "Bolsa grande o prenda amplia" },
    { word: "sal", def: "Condimento mineral blanco" },
    { word: "salamandra", def: "Anfibio de cuerpo alargado" },
    { word: "salón", def: "Sala principal de una casa" },
    { word: "salto", def: "Acción de elevarse del suelo" },
    { word: "sandalia", def: "Calzado abierto" },
    { word: "sandía", def: "Fruta grande y refrescante" },
    { word: "sargento", def: "Grado militar" },
    { word: "sartén", def: "Utensilio de cocina" },
    { word: "satélite", def: "Cuerpo que gira alrededor de otro" },
    { word: "sauce", def: "Árbol de ramas caídas" },
    { word: "secreto", def: "Lo que se oculta" },
    { word: "seda", def: "Fibra fina y brillante" },
    { word: "selva", def: "Bosque tropical espeso" },
    { word: "sello", def: "Marca oficial o cierre" },
    { word: "semáforo", def: "Dispositivo que regula el tráfico" },
    { word: "serpiente", def: "Reptil alargado sin patas" },
    { word: "servilleta", def: "Paño o papel para limpiarse al comer" },
    { word: "señal", def: "Indicio o marca" },
    { word: "siembra", def: "Acción de sembrar" },
    { word: "siesta", def: "Sueño corto después de comer" },
    { word: "silencio", def: "Ausencia de ruido" },
    { word: "silla", def: "Asiento con respaldo" },
    { word: "símbolo", def: "Signo que representa algo" },
    { word: "sincero", def: "Que dice la verdad" },
    { word: "sitio", def: "Lugar" },
    { word: "sobre", def: "Cubierta para cartas" },
    { word: "socorro", def: "Ayuda en un peligro" },
    { word: "sol", def: "Estrella del sistema solar" },
    { word: "soldado", def: "Miembro del ejército" },
    { word: "sollozo", def: "Llanto con respiración entrecortada" },
    { word: "sombrero", def: "Prenda para cubrir la cabeza" },
    { word: "sonrisa", def: "Gesto de alegría o agrado" },
    { word: "sorpresa", def: "Impresión por algo inesperado" },
    { word: "submarino", def: "Nave que puede moverse bajo el agua" },
    { word: "sudor", def: "Líquido que sale por la piel" },
    { word: "sueño", def: "Acto de dormir o imagen del dormir", contains: true },
  ],
  T: [
    { word: "tormenta", def: "Fenómeno atmosférico violento" },
    { word: "tesoro", def: "Conjunto de riquezas guardadas" },
    { word: "telaraña", def: "Tela fabricada por la araña" },
    { word: "trampa", def: "Artificio para cazar o engañar" },
    { word: "tobogán", def: "Rampa para deslizarse" },
    { word: "ternura", def: "Cariño delicado" },
    { word: "trébol", def: "Planta de tres folíolos" },
    { word: "trueno", def: "Ruido fuerte de las tormentas" },
    { word: "tinta", def: "Líquido para escribir" },
    { word: "talismán", def: "Objeto con supuestos poderes de suerte" },
    { word: "tabla", def: "Pieza plana de madera" },
    { word: "tablero", def: "Superficie de juego o mesa" },
    { word: "tacto", def: "Sentido de tocar" },
    { word: "tahona", def: "Molino o panadería antigua" },
    { word: "tallo", def: "Parte principal de una planta" },
    { word: "tambor", def: "Instrumento de percusión" },
    { word: "tapa", def: "Cubierta de un recipiente" },
    { word: "tarde", def: "Parte final del día" },
    { word: "tarea", def: "Trabajo o deber" },
    { word: "tarjeta", def: "Lámina pequeña con datos o para pagar" },
    { word: "tazón", def: "Recipiente ancho y hondo" },
    { word: "teatro", def: "Arte escénico o edificio para representarlo" },
    { word: "techo", def: "Parte superior interior de una habitación" },
    { word: "tecla", def: "Pieza de un teclado o instrumento" },
    { word: "tejado", def: "Cubierta exterior de una casa" },
    { word: "templo", def: "Edificio destinado al culto" },
    { word: "tenedor", def: "Cubierto con púas" },
    { word: "tensión", def: "Fuerza de estiramiento o estado nervioso" },
    { word: "terciopelo", def: "Tela suave y afelpada" },
    { word: "termómetro", def: "Instrumento para medir temperatura" },
    { word: "terrario", def: "Recipiente con tierra y plantas" },
    { word: "tierra", def: "Planeta o suelo" },
    { word: "tijera", def: "Instrumento para cortar" },
    { word: "tilo", def: "Árbol de flores aromáticas" },
    { word: "timón", def: "Pieza para dirigir una nave o vehículo" },
    { word: "tirano", def: "Gobernante cruel" },
    { word: "tirita", def: "Tira adhesiva para heridas" },
    { word: "titán", def: "Gigante mitológico o persona muy destacada" },
    { word: "toalla", def: "Pieza de tela para secarse" },
    { word: "tomate", def: "Fruto rojo comestible" },
    { word: "tono", def: "Grado de intensidad o color" },
    { word: "torre", def: "Construcción alta" },
    { word: "tortuga", def: "Reptil con caparazón" },
    { word: "trabajo", def: "Actividad realizada con esfuerzo" },
    { word: "traje", def: "Conjunto de vestir" },
    { word: "trébol", def: "Hierba pequeña asociada a la suerte" },
    { word: "tribuna", def: "Plataforma elevada o graderío" },
    { word: "trigo", def: "Cereal de espigas" },
    { word: "tronco", def: "Parte principal del árbol" },
    { word: "turno", def: "Orden para actuar o trabajar" },
  ],
  U: [
    { word: "utopía", def: "Proyecto ideal difícil de realizar" },
    { word: "umbral", def: "Entrada o comienzo de algo" },
    { word: "universo", def: "Conjunto de todo lo que existe" },
    { word: "urraca", def: "Ave blanca y negra de cola larga" },
    { word: "uva", def: "Fruto de la vid" },
    { word: "ungüento", def: "Preparado medicinal pastoso" },
    { word: "utensilio", def: "Instrumento de uso práctico" },
    { word: "unicornio", def: "Animal fabuloso con un cuerno" },
    { word: "ubicar", def: "Situar en un lugar" },
    { word: "ubre", def: "Pecho de la hembra de mamíferos" },
    { word: "ufano", def: "Satisfecho y orgulloso" },
    { word: "ultramar", def: "Territorio más allá del mar" },
    { word: "ulular", def: "Dar gritos o sonidos prolongados" },
    { word: "umbela", def: "Tipo de inflorescencia" },
    { word: "unidad", def: "Cualidad de ser uno o elemento básico" },
    { word: "uniforme", def: "Igual en forma o vestido reglamentario" },
    { word: "unir", def: "Juntar" },
    { word: "universidad", def: "Centro de estudios superiores" },
    { word: "uno", def: "Número primero" },
    { word: "urbanismo", def: "Planificación de ciudades" },
    { word: "urdimbre", def: "Hilos longitudinales en un tejido" },
    { word: "urgencia", def: "Necesidad de pronta atención" },
    { word: "urna", def: "Caja para votos o cenizas" },
    { word: "usar", def: "Servirse de algo" },
    { word: "usina", def: "Instalación industrial o eléctrica" },
    { word: "usual", def: "Habitual" },
    { word: "usuario", def: "Persona que utiliza un servicio" },
    { word: "ustión", def: "Quemadura leve por calor", contains: true },
    { word: "útil", def: "Que sirve para algo" },
    { word: "uterino", def: "Relativo al útero" },
    { word: "utillaje", def: "Conjunto de herramientas" },
    { word: "último", def: "Que va al final" },
    { word: "ultravioleta", def: "Radiación más allá del violeta" },
    { word: "ultrasonido", def: "Sonido de alta frecuencia" },
    { word: "umbrío", def: "Con mucha sombra" },
    { word: "uncir", def: "Poner yugo a animales" },
    { word: "undular", def: "Moverse formando ondas" },
    { word: "ungulado", def: "Animal con pezuñas" },
    { word: "urbe", def: "Ciudad grande" },
    { word: "urdir", def: "Preparar hilos o tramar algo" },
    { word: "urel", def: "Pez de mar", contains: true },
    { word: "urna", def: "Recipiente cerrado para depositar algo" },
    { word: "usar", def: "Hacer servir una cosa" },
    { word: "usufructo", def: "Derecho a disfrutar bienes ajenos" },
    { word: "utero", def: "Órgano donde se gesta el embrión" },
    { word: "utópico", def: "Propio de la utopía" },
    { word: "uve", def: "Nombre de la letra v" },
    { word: "ubicuo", def: "Que está presente en todas partes" },
    { word: "uva pasa", def: "Uva seca" },
    { word: "urbanidad", def: "Buenas maneras en sociedad" },
  ],
  V: [
    { word: "volcán", def: "Abertura terrestre por donde salen lava y gases" },
    { word: "vendaval", def: "Viento fuerte" },
    { word: "vértigo", def: "Sensación de que todo gira" },
    { word: "vasija", def: "Recipiente para líquidos o alimentos" },
    { word: "velero", def: "Embarcación impulsada por velas" },
    { word: "viñedo", def: "Terreno plantado de vides" },
    { word: "veneno", def: "Sustancia tóxica" },
    { word: "vigía", def: "Persona que observa desde un punto alto" },
    { word: "vanguardia", def: "Parte adelantada o innovadora" },
    { word: "vergel", def: "Huerto o jardín frondoso" },
    { word: "vaca", def: "Hembra del toro" },
    { word: "vacío", def: "Falta de contenido" },
    { word: "valle", def: "Llanura entre montañas" },
    { word: "vapor", def: "Gas producido por un líquido" },
    { word: "vara", def: "Palo largo y delgado" },
    { word: "vecino", def: "Persona que vive cerca" },
    { word: "vela", def: "Pieza de cera con mecha o lona de barco" },
    { word: "velocidad", def: "Rapidez de movimiento" },
    { word: "ventana", def: "Abertura en una pared" },
    { word: "verano", def: "Estación más calurosa" },
    { word: "verbo", def: "Palabra que expresa acción o estado" },
    { word: "verdad", def: "Conformidad con la realidad" },
    { word: "verde", def: "Color de la hierba" },
    { word: "vereda", def: "Camino angosto" },
    { word: "verso", def: "Línea de un poema" },
    { word: "vestido", def: "Prenda o conjunto de ropa" },
    { word: "viaje", def: "Desplazamiento de un lugar a otro" },
    { word: "vibración", def: "Movimiento oscilatorio rápido" },
    { word: "vid", def: "Planta que da uvas" },
    { word: "vida", def: "Existencia de los seres vivos" },
    { word: "vidrio", def: "Material duro y transparente" },
    { word: "viento", def: "Aire en movimiento" },
    { word: "viernes", def: "Sexto día de la semana" },
    { word: "viga", def: "Pieza horizontal de construcción" },
    { word: "villa", def: "Población pequeña o casa de recreo" },
    { word: "vinagre", def: "Líquido agrio usado en cocina" },
    { word: "vino", def: "Bebida alcohólica de uva" },
    { word: "violín", def: "Instrumento musical de cuerda" },
    { word: "viruta", def: "Lámina fina desprendida al cepillar madera" },
    { word: "vista", def: "Sentido de ver" },
    { word: "vitrina", def: "Mueble con cristal para exhibir objetos" },
    { word: "viuda", def: "Mujer cuyo cónyuge ha muerto" },
    { word: "vivo", def: "Que tiene vida" },
    { word: "volante", def: "Rueda para dirigir un vehículo" },
    { word: "volumen", def: "Magnitud del espacio ocupado" },
    { word: "voto", def: "Expresión de una elección" },
    { word: "voz", def: "Sonido producido al hablar" },
    { word: "vuelta", def: "Movimiento de retorno o giro" },
    { word: "vuelo", def: "Acción de volar" },
    { word: "vulcano", def: "Nombre mitológico del dios del fuego" },
  ],
  W: [
    { word: "kiwi", def: "Fruto comestible de pulpa verde", contains: true },
    { word: "web", def: "Red informática mundial de páginas enlazadas", contains: false },
    { word: "wifi", def: "Tecnología de conexión inalámbrica", contains: false },
    { word: "wéstern", def: "Género ambientado en el oeste americano", contains: false },
    { word: "waterpolo", def: "Deporte acuático de equipo", contains: false },
    { word: "wafle", def: "Masa cocida en rejilla, también llamada gofre", contains: false },
    { word: "walkie", def: "Radiotransmisor portátil", contains: false },
    { word: "wapití", def: "Gran ciervo norteamericano", contains: false },
    { word: "watt", def: "Unidad de potencia", contains: false },
    { word: "weimarés", def: "Raza de perro de caza", contains: false },
    { word: "whisky", def: "Bebida alcohólica destilada", contains: false },
    { word: "windsurf", def: "Deporte de vela sobre tabla", contains: false },
    { word: "wolframio", def: "Metal también llamado tungsteno", contains: false },
    { word: "wombat", def: "Marsupial australiano", contains: false },
    { word: "won", def: "Moneda de Corea", contains: false },
    { word: "wrap", def: "Comida enrollada en tortilla", contains: false },
    { word: "wéstern", def: "Película del Lejano Oeste", contains: false },
    { word: "walkman", def: "Reproductor portátil de música", contains: false },
    { word: "washi", def: "Papel tradicional japonés", contains: false },
    { word: "waterpolo", def: "Juego en piscina con pelota", contains: false },
    { word: "windsurfista", def: "Persona que practica windsurf", contains: false },
    { word: "wifímetro", def: "Medidor informal de señal wifi", contains: false },
    { word: "whiskería", def: "Local nocturno, uso coloquial", contains: false },
    { word: "wok", def: "Sartén profunda asiática", contains: false },
    { word: "wasabi", def: "Condimento japonés picante", contains: false },
    { word: "webcam", def: "Cámara conectada a un ordenador", contains: false },
    { word: "webinario", def: "Seminario en línea", contains: false },
    { word: "windsor", def: "Tipo de nudo de corbata", contains: false },
    { word: "waflera", def: "Aparato para hacer wafles", contains: false },
    { word: "waterline", def: "Línea de flotación, anglicismo de uso técnico", contains: false },
    { word: "whippet", def: "Raza de perro" , contains: false },
    { word: "wap", def: "Protocolo antiguo de internet móvil", contains: false },
    { word: "westernizado", def: "Adaptado a costumbres occidentales", contains: false },
    { word: "walkthrough", def: "Guía paso a paso, anglicismo de videojuegos", contains: false },
    { word: "wurlitzer", def: "Tipo de organillo o máquina de música", contains: false },
    { word: "windscreen", def: "Parabrisas, uso técnico en inglés", contains: false },
    { word: "wattímetro", def: "Instrumento para medir potencia eléctrica", contains: false },
    { word: "wélter", def: "Categoría de peso en boxeo", contains: false },
    { word: "washingtonia", def: "Tipo de palmera", contains: false },
    { word: "webmaster", def: "Responsable de un sitio web", contains: false },
    { word: "whiskera", def: "Variante coloquial de whiskería", contains: false },
    { word: "windsurfear", def: "Practicar windsurf", contains: false },
    { word: "wolfram", def: "Variante de wolframio", contains: false },
    { word: "wéstern", def: "Estilo narrativo del oeste", contains: false },
    { word: "waypoint", def: "Punto de referencia en navegación", contains: false },
    { word: "wireless", def: "Sin cables", contains: false },
    { word: "watchman", def: "Vigilante, anglicismo ocasional", contains: false },
    { word: "windsoriana", def: "Relativa a Windsor", contains: false },
    { word: "wagneriano", def: "Relativo a Wagner", contains: false },
    { word: "westfalia", def: "Región histórica europea", contains: false },
  ],
  X: [
    { word: "xilófono", def: "Instrumento de percusión con láminas de madera", contains: false },
    { word: "oxígeno", def: "Gas esencial para la respiración", contains: true },
    { word: "examen", def: "Prueba para evaluar conocimientos", contains: true },
    { word: "taxista", def: "Persona que conduce un taxi", contains: true },
    { word: "boxeo", def: "Deporte de combate con guantes", contains: true },
    { word: "elixir", def: "Sustancia maravillosa o curativa", contains: true },
    { word: "galaxia", def: "Conjunto enorme de estrellas", contains: true },
    { word: "auxilio", def: "Ayuda o socorro", contains: true },
    { word: "xenón", def: "Gas noble", contains: false },
    { word: "xerografía", def: "Procedimiento de copia en seco", contains: false },
    { word: "xifoides", def: "Relativo a la espada o apéndice del esternón", contains: false },
    { word: "xilografía", def: "Grabado en madera", contains: false },
    { word: "xilófago", def: "Que roe o come madera", contains: false },
    { word: "xiloteca", def: "Colección de maderas clasificadas", contains: false },
    { word: "xenofobia", def: "Rechazo a los extranjeros", contains: false },
    { word: "xerófilo", def: "Adaptado a lugares secos", contains: false },
    { word: "xeroftalmia", def: "Sequedad anormal del ojo", contains: false },
    { word: "xilema", def: "Tejido vegetal conductor de savia", contains: false },
    { word: "xilofonista", def: "Persona que toca el xilófono", contains: false },
    { word: "xenial", def: "Relativo a la hospitalidad", contains: false },
    { word: "expreso", def: "Tren rápido o café concentrado", contains: true },
    { word: "texto", def: "Conjunto de palabras escritas", contains: true },
    { word: "extraño", def: "Raro o ajeno", contains: true },
    { word: "próximo", def: "Cercano en tiempo o espacio", contains: true },
    { word: "éxito", def: "Resultado feliz", contains: true },
    { word: "mixto", def: "Compuesto de varios elementos", contains: true },
    { word: "exacto", def: "Preciso, sin error", contains: true },
    { word: "exilio", def: "Separación forzada de la patria", contains: true },
    { word: "tóxico", def: "Que contiene veneno", contains: true },
    { word: "lexema", def: "Unidad léxica mínima", contains: true },
    { word: "máximo", def: "Valor más alto", contains: true },
    { word: "convexo", def: "Curvado hacia fuera", contains: true },
    { word: "anexo", def: "Adjunto o añadido", contains: true },
    { word: "éxtasis", def: "Estado de intensa emoción", contains: true },
    { word: "exótico", def: "Extraño y procedente de otro lugar", contains: true },
    { word: "taxonomía", def: "Clasificación ordenada de seres o cosas", contains: true },
    { word: "axioma", def: "Proposición evidente que no necesita demostración", contains: true },
    { word: "máxime", def: "Principalmente", contains: true },
    { word: "oxidar", def: "Combinar con oxígeno", contains: true },
    { word: "xerojardinería", def: "Jardinería de bajo consumo de agua", contains: false },
    { word: "expiar", def: "Purgar una culpa", contains: true },
    { word: "hexágono", def: "Polígono de seis lados", contains: true },
    { word: "ortodoxo", def: "Conforme a una doctrina tradicional", contains: true },
    { word: "sexto", def: "Que ocupa el lugar número seis", contains: true },
    { word: "xantina", def: "Compuesto orgánico", contains: false },
    { word: "xerocopia", def: "Fotocopia", contains: false },
    { word: "exprimir", def: "Sacar jugo apretando", contains: true },
    { word: "cruce", def: "Lugar donde se cruzan caminos", contains: true },
    { word: "flexión", def: "Acción de doblar", contains: true },
    { word: "xenofilia", def: "Aprecio por lo extranjero", contains: false },
  ],
  Y: [
    { word: "yacimiento", def: "Lugar donde se encuentran minerales o restos" },
    { word: "yunque", def: "Bloque de hierro para forjar" },
    { word: "yate", def: "Embarcación de recreo" },
    { word: "yema", def: "Parte amarilla del huevo" },
    { word: "yedra", def: "Planta trepadora de hojas verdes", contains: false },
    { word: "yegua", def: "Hembra del caballo" },
    { word: "yugo", def: "Instrumento para uncir animales" },
    { word: "yodo", def: "Elemento químico usado como antiséptico" },
    { word: "yacente", def: "Tendido o acostado" },
    { word: "yacija", def: "Lecho o lugar donde se descansa" },
    { word: "yantar", def: "Comer, en uso antiguo" },
    { word: "yarda", def: "Medida de longitud anglosajona" },
    { word: "yema", def: "Brote tierno de una planta o parte del huevo" },
    { word: "yerba", def: "Planta pequeña o hierba" },
    { word: "yerno", def: "Esposo de una hija" },
    { word: "yesería", def: "Trabajo ornamental en yeso" },
    { word: "yeso", def: "Material de construcción blanco" },
    { word: "yihad", def: "Esfuerzo religioso en contexto islámico" },
    { word: "yincana", def: "Juego o competición de pruebas", contains: false },
    { word: "yo", def: "Pronombre de primera persona" },
    { word: "yoduro", def: "Compuesto del yodo" },
    { word: "yogur", def: "Leche fermentada" },
    { word: "yoyó", def: "Juguete que sube y baja con un cordón" },
    { word: "yucca", def: "Planta ornamental o yuca, grafía internacional", contains: false },
    { word: "yuca", def: "Planta tropical de raíz comestible" },
    { word: "yugada", def: "Terreno que puede arar una yunta" },
    { word: "yugo", def: "Pieza de madera para unir animales de tiro" },
    { word: "yunta", def: "Par de animales de labor" },
    { word: "yunquear", def: "Trabajar sobre yunque", contains: false },
    { word: "yacija", def: "Lecho improvisado" },
    { word: "yacón", def: "Planta andina de raíz dulce" },
    { word: "yak", def: "Bóvido asiático lanudo", contains: false },
    { word: "yarará", def: "Serpiente venenosa sudamericana", contains: false },
    { word: "yerro", def: "Falta o error" },
    { word: "yerno", def: "Marido de la hija" },
    { word: "yodar", def: "Tratar con yodo", contains: false },
    { word: "yema", def: "Parte sensible de la punta de los dedos", contains: false },
    { word: "yelmo", def: "Casco antiguo de armadura", contains: false },
    { word: "yente", def: "Casamentera en tradición judía", contains: false },
    { word: "yerbal", def: "Terreno poblado de hierbas" },
    { word: "yermo", def: "Terreno estéril o despoblado" },
    { word: "yesquero", def: "Estuche para llevar yesca o encendedor" },
    { word: "yubarta", def: "Ballena jorobada", contains: false },
    { word: "yacija", def: "Cama improvisada en el suelo" },
    { word: "yero", def: "Planta leguminosa", contains: false },
    { word: "yuxta", def: "Junto a, en composición", contains: false },
    { word: "yuxtaponer", def: "Poner una cosa junto a otra", contains: false },
    { word: "yip", def: "Interjección de alegría", contains: false },
    { word: "yaguar", def: "Variante antigua de jaguar", contains: false },
    { word: "yamaní", def: "Arroz integral de grano fino", contains: false },
  ],
  Z: [
    { word: "zafiro", def: "Piedra preciosa azul" },
    { word: "zarpa", def: "Garra de algunos animales" },
    { word: "zanja", def: "Excavación larga y estrecha" },
    { word: "zócalo", def: "Parte inferior de una pared" },
    { word: "zarzamora", def: "Fruto negro de la zarza" },
    { word: "zenit", def: "Punto del cielo sobre la cabeza" },
    { word: "zodiaco", def: "Franja celeste dividida en doce signos" },
    { word: "zorro", def: "Mamífero carnívoro de hocico alargado" },
    { word: "zumbido", def: "Ruido continuado de algunos insectos" },
    { word: "zumo", def: "Líquido extraído de frutas" },
    { word: "zagal", def: "Pastor joven" },
    { word: "zahorí", def: "Persona a la que se atribuye hallar agua", contains: false },
    { word: "zanahoria", def: "Raíz anaranjada comestible" },
    { word: "zanco", def: "Palo alto para andar elevado" },
    { word: "zángano", def: "Abeja macho o persona perezosa" },
    { word: "zapa", def: "Acción de cavar o labor de mina" },
    { word: "zapato", def: "Calzado que cubre el pie" },
    { word: "zar", def: "Antiguo emperador de Rusia" },
    { word: "zarigüeya", def: "Marsupial americano" },
    { word: "zarzuela", def: "Género musical escénico español" },
    { word: "zascandil", def: "Persona inquieta y de poca formalidad" },
    { word: "zebra", def: "Variante de cebra", contains: false },
    { word: "zeca", def: "Ceca o casa de moneda, grafía antigua", contains: false },
    { word: "zelote", def: "Miembro de un grupo judío antiguo", contains: false },
    { word: "zen", def: "Escuela budista de meditación" },
    { word: "zepelín", def: "Globo dirigible", contains: false },
    { word: "zigzag", def: "Línea con ángulos alternos" },
    { word: "zinc", def: "Metal blanco azulado" },
    { word: "zíngaro", def: "Gitano, uso literario" },
    { word: "zoquete", def: "Trozo de madera o persona torpe" },
    { word: "zorzal", def: "Ave de canto agradable" },
    { word: "zozobra", def: "Inquietud o angustia" },
    { word: "zulú", def: "Perteneciente a un pueblo africano" },
    { word: "zurcir", def: "Coser una rotura" },
    { word: "zurdo", def: "Que usa mejor la mano izquierda" },
    { word: "zurrón", def: "Bolsa grande de cuero" },
    { word: "zutano", def: "Nombre que designa a persona cualquiera" },
    { word: "zambomba", def: "Instrumento musical popular" },
    { word: "zambullida", def: "Acción de meterse de golpe en el agua" },
    { word: "zasca", def: "Respuesta cortante, coloquial" },
    { word: "zóster", def: "Infección vírica conocida como culebrilla" },
    { word: "zueco", def: "Calzado de madera o suela gruesa" },
    { word: "zafra", def: "Temporada de recolección de caña o aceituna" },
    { word: "zarandeo", def: "Movimiento brusco de un lado a otro" },
    { word: "zarco", def: "De color azul claro en los ojos" },
    { word: "zíper", def: "Cierre de cremallera", contains: false },
    { word: "zoonosis", def: "Enfermedad transmitida de animales a humanos" },
    { word: "zoológico", def: "Lugar donde se exhiben animales" },
    { word: "zote", def: "Persona torpe", contains: false },
    { word: "zurrar", def: "Golpear o curtir pieles" },
  ],
};

export default WORD_BANK;
